### ISSUE TITLE
Set up visual regression tests

### ISSUE THREAD

**Issue by contolini** [cfpb/design-stories#23]
## Tasks

- [ ] Research Storybook-compatible visual regression test frameworks (maybe [lost pixel](https://docs.lost-pixel.com/user-docs/)?)
- [ ] Select a reasonable one and configure it with this repo
- [ ] Write a visual regression test and let us know how it goes.

**Comment by meissadia** [comment]
## Option: [Chromatic](https://www.chromatic.com/) 
This is the [Storybook-recommended tool](https://storybook.js.org/docs/6.5/react/writing-tests/visual-testing) and it seems quite promising.  
 
[Demo video](https://www.youtube.com/watch?v=9o6uB1X-LZ8)
 
I signed up with an email address, as opposed to authenticating via GitHub, which seems to disable a couple of the more advanced (but still free) features:
- UI Review: Provides a visual overview of all observable UI changes that team members can review and comment/approve/deny.
- TurboSnap: Helps to minimize the number of snapshots generated for each build (free plan provides 5,000 snapshots/month) by focusing only on components that have code changes.  
 
### Pros
- Chromatic has been pretty easy to setup
- Has strong documentation that covers a variety of use cases. Ex: [GitHub integration](https://www.chromatic.com/docs/github-actions).
- Solid free tier - 5K snapshots (visual comparisons) per month
- Looks like new users get an extra 75K snapshots included in the first month's limit to provide leeway in getting things setup.  

### Needs clarification
- Would 5K snapshots/month be sufficient for a Bureau-wide tool that multiple teams could be modifying at once?  Seems like 1 story = 1 snapshot, so we currently generate 52 snapshots per run. 
- Free plan only supports Chrome snapshots.  Do we need IE or Firefox support?
- Do all collaborators have Github accounts?  
  - How easy will it be add non-devs as reviewers?
- Wise for me to setup Github integration for this tool or should the integration be owned by a CFPB dev?
- Should we just pick a tool and run with it until it becomes clear that it's not working for the team?  Or should we continue to evaluate alternatives, poll the team, and move forward with our consensus favorite?

### Next Steps
- Use Github auth to setup Chromatic project to maximize feature availability and github integration.
- Test github integration
- Evaluate workflow for identifying and approving/denying UI changes
- Ensure all collaborators can access the Chromatic project

**Comment by contolini** [comment]
> Should we just pick a tool and run with it

Yes, go for it!

> Would 5K snapshots/month be sufficient for a Bureau-wide tool that multiple teams could be modifying at once?

If we hit this limit and enjoy the tool we can enlist procurement guru @harrisj for advice.

**Comment by contolini** [comment]
The Guardian has a [neat trick](https://github.com/guardian/csnx/blob/0503d9f24508211df3a48d1bbeb1873d9faf6fe8/.github/workflows/ci.yml#L36) to save on Chromatic runs. From their [readme](https://github.com/guardian/csnx#chromatic):

> To run Chromatic (for visual regression testing) on a PR, add the run_chromatic label to the PR in Github. The Chromatic tests are required to pass by CI, so this will need to be done at least once before a PR is merged. We recommend you only add the label once you are happy with any changes made and have checked for visual regressions manually first.
