### ISSUE TITLE
Upgrade Storybook to v7

### ISSUE THREAD

**Issue by contolini** [cfpb/design-stories#26]
We're on v6.5.16 and it's nudging us to upgrade to v7 for some [neat new features](https://storybook.js.org/releases/7.0).

<img width="819" alt="image" src="https://user-images.githubusercontent.com/1060248/233123024-9817845d-f903-4605-8b41-fbb5d0591e2e.png">

## Task

- [x] Update npm dependencies using yarn.
- [x] Update Story format to CSF3.0
  - [x] Others complete
  - [x] TableComplex
  - [x] TableSimple
  - [x] TextInput
- [x] Address errors blocking Netlify build/deploy
  - [x] Could not find a declaration file for module '@cfpb/cfpb-expandables/src/Expandable'
  - [x] [Page.tsx] Expected 1 arguments, but got 0
  - [x] Cannot find type definition file for 'vite-plugin-pwa/client'
  - [x] `yarn build-storybook` errors about stuff that cannot be named...?
  - [x] Some kind of Typescript error 😭.  My guess is that it is looking in the wrong directory - `yarn build-storybook` specifies the output be saved to `dist-storybook` but this plugin seems to be looking in `dist`. 
     ```
     1:42:55 PM: [vite:dts] Start generate declaration files...
     1:43:01 PM: ERR! Error: ENOENT: no such file or directory, open '/opt/build/repo/dist/index.d.ts'
     ```
     - [Screenshot of full error](https://github.com/cfpb/design-stories/issues/26#issuecomment-1518274619)
     - [Deployment logs](https://app.netlify.com/sites/cfpb-design-stories/deploys/6442e6f69804720008ac6612)
- [ ] Verify nothing is broken.
- [ ] Optional: Check out the new features and let us know if anything is particularly exciting.

**Comment by meissadia** [comment]
Last remaining error blocking Netlify deployments

<img width="1163" alt="Screen Shot 2023-04-21 at 1 51 16 PM" src="https://user-images.githubusercontent.com/2592907/233723842-c02d0c57-9afd-4a5c-87e5-9652765f24f8.png">
