### ISSUE TITLE
Add a page banner component

### ISSUE THREAD

**Issue by contolini** [cfpb/design-stories#27]
## Context

Our products often have a banner at the top of the page with a government website disclaimer, sometimes with [language links](https://www.consumerfinance.gov/).

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/1060248/233129995-039a11d4-c425-432f-8569-1e6fee2ee8ae.png">

### Pre-requisites

- [x] You have a machine with a Node.js v16 and yarn installed.

## Task

- [x] Clone, [set up](https://github.com/cfpb/design-stories#development), familiarize yourself with this repo and [Storybook](https://storybook.js.org/docs/react/get-started/introduction). Post a comment below if you run into any issues.
- [x] Create a `Banner.tsx` and `Banner.stories.tsx` file in the [components](https://github.com/cfpb/design-stories/tree/main/src/components) directory (use other filenames if preferred).
- [x] Create a React/Typescript version of cf.gov's [global eyebrow](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/v1/jinja2/v1/includes/molecules/global-eyebrow.html) jinja2 template file.
- [x] The language links and phone number should be optional and configurable. It's probably best to keep them generic with a `links` prop instead of hard-coding anything.

Tips:

- The [react-uswds banner](https://trussworks.github.io/react-uswds/?path=/story/components-banner--custom-banner) is nearly identical to CFPB's so you should probably just copy/paste one (or all?) of [their banners](https://github.com/trussworks/react-uswds/tree/main/src/components/banner). Fun fact: The reason they look so similar is because USWDS copied the pattern from CFPB ~ 10 years ago. Hooray for coding in the open!
- It doesn't have to be a 1-to-1 duplicate of CFPB's HTML component. Just do an MVP version.
