### ISSUE TITLE
Add tests for Checkbox component

### ISSUE THREAD

**Issue by contolini** [cfpb/design-stories#33]
We have [React Testing Library](https://testing-library.com/) and [Vitest](https://vitest.dev/) (as a test runner) set up for our components' unit tests.

## Tasks:

- [ ] Create a `<component-name>.test.tsx` file
- [ ] Run `yarn test` to start Vitest, it'll automatically run tests when the above file changes.
- [ ] Write some tests, aim for 100% code coverage.

## Useful links:

- [Example test file](https://github.com/cfpb/design-stories/blob/main/src/components/Button.test.tsx)
- [RTL cheatsheet](https://testing-library.com/docs/react-testing-library/cheatsheet)
- [RTL tutorial](https://www.robinwieruch.de/react-testing-library/)
- [RTL common mistakes](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library)
